using UnityEngine;
using System.Collections;

static public class BaizVariableScript {
	
	// 领取奖励标记名 ...
	
	static public float DEPTH_OFFSET = 0.45f;
	static public float DEPTH_TOP1 = -4f;
	static public float DEPTH_TOPMOST_OFFSET = -5f;
	
	// 召回,加速,观察...
	static public int COMBAT_OP_ARMY_BACK = 307;
	static public int COMBAT_OP_ARMY_ACCEL = 308;
	static public int COMBAT_OP_ARMY_GUANZHAN = 309;
	static public int COMBAT_OP_ARMY_BACKING = 311;
	static public int COMBAT_HONOR_NO_JOIN_UNION = 313;
	static public int COMBAT_HONOR_NO_GRAIL = 317;
	static public int COMBAT_HONOR_GAMEOVER = 327;
	
	// 武将名称 ...
	static public int COMBAT_GENERAL_PVE_WORLDCITY = 322;
	static public int COMBAT_GENERAL_PVE_WORLDGOLDMINE = 323;
	static public int COMBAT_GENERAL_PVE_BAIZHANBUDAI = 324;
	static public int COMBAT_GENERAL_PVE_NANZHENGBEIZHAN = 325;
	static public int COMBAT_GENERAL_PVE_RAID = 326;
	
	// 战斗类型/意图 ....
	static public int COMBAT_TYPE_PVE_WORLDGOLDMINE = 401;		// 世界金矿 ...
	static public int COMBAT_TYPE_INSTANCE_BAIZHANBUDAI = 402;	// 百战不殆 ...
	static public int COMBAT_TYPE_INSTANCE_NANZHENGBEIZHAN = 403;	// 南征北战 ...
	static public int COMBAT_TYPE_PVE_RAID = 404;					// 蛮族营地 ...
	static public int COMBAT_TYPE_PVE_WORLDCITY = 316;				// 荣耀之城 ...
	static public int COMBAT_TYPE_WORLD_RESOURCE = 336;				// 世界资源 ... 
	static public int COMBAT_TYPE_WORLD_RESOURCE_DESC = 337;  			//世界资源描述 

	static public int COMBAT_STATUS_MARCH = 405;
	static public int COMBAT_STATUS_BACKING = 406;
	static public int COMBAT_PLAN_PVE = 407;
	static public int COMBAT_PLAN_LOOT = 408;
	static public int COMBAT_PLAN_PVP = 409;
	static public int COMBAT_PLAN_DEFENSE = 410;
	static public int COMBAT_TEXT_PVE_GENERAL = 411;
	static public int COMBAT_MSG_ARMY_BACK_ASK = 449;			// 军队召回寻问 ...
	
	// 消息二次确定 ....
	static public int WORLDGOLDMINE_GIVEUP = 412;				// 君主已经占领了一个金矿资源,是否放弃金矿 ...
	static public int WORLDGOLDMINE_NO_ONE = 413;				// 君主还未占领金矿资源,赶快整备部队去攻占金矿吧 ...
	static public int WORLDGOLDMINE_NPC_1 = 414;				// 特级金矿守卫 ...
	static public int WORLDGOLDMINE_NPC_2 = 415;				// 高级金矿守卫 ...
	static public int WORLDGOLDMINE_NPC_3 = 416;				// 中级金矿守卫 ...
	static public int WORLDGOLDMINE_NPC_4 = 417; 				// 低级金矿守卫 ...
	
	// 聊天信息 ...
	static public int CHAT_MSG_INSTANCE_BAIZHANBUDAI = 422;		// 百战消息 ...
	static public int CHAT_MSG_INSTANCE_NANZHENGBEIZHAN = 423;	//
	static public int CHAT_MSG_ADDLOOT_BAIZHANBUDAI = 424; 		//
	static public int CHAT_MSG_ADDLOOT_NANZHENGBEIZHAN = 425; 	// 
	static public int CHAT_MSG_ONLINE_BAIZHANBUDAI = 436;		// 上线提醒 ...
	static public int CHAT_MSG_ONLINE_NANZHENGBEIZHAN = 437;	// 上线提醒 ...
	static public int CHAT_MSG_QUEST_GUIDE_SKIP_OVER = 443;		// 确定跳过新手引导 ...
	static public int CHAT_MSG_QUEST_GUIDE_FINI_ASK = 444;		// 任务指导最后一步寻问 ...
	static public int CHAT_MSG_BAIZHANBUDAI_IS_FREE = 445;		//  ...
	static public int CHAT_MSG_NANZHENGBEIZHAN_IS_FREE = 446;	// 任务指导最后一步寻问 ...
	static public int CHAT_MSG_QUEST_GUIDE_NEWPLAYER = 447;		// 新手乍到 ...
	static public int PICKING_GENERAL_NO_ARMY = 421;			// 武将未带领士兵, 不能出战 ...
	static public int PICKING_GENERAL_NO_ARMY_SUPPORT = 448;	// 没有配置士兵的开奖的 ...
	static public int CHAT_MSG_ONLINE_BAIZHANBUDAI_RST_READY = 450;	// 准备攻打...
	static public int CHAT_MSG_ONLINE_NANZHENGBEIZHAN_RST_READY = 451; // 准备攻打 ...
	
	// 道具使用 ...
	static public int ITEM_CITY_MOVABLE_REEL_IS_NULL = 426;			// 迁城卷轴 ...
	static public int ITEM_CITY_MOVABLE_CONSUME_OK = 427;
	
	// 迁城错误 ...
	static public int CITY_MOVABLE_RST_ALREADY_PLAYER = 428;		// 已经有其他玩家了 ...
	static public int CITY_MOVABLE_RST_ITEM_IS_NULL = 429;			// 缺少卷轴 ...
	static public int CITY_MOVABLE_RST_CANNOT_BUILD = 430;			// 这地方不能建城 ...
	static public int CITY_MOVABLE_RST_POSITION_IS_NULL = 431;		// 无效坐标 ...
	static public int CITY_MOVABLE_RST_CANNOT_MOVE = 432;			// 不能移动 ...
	// 错误提示ID ...
	
	// 副本删除错误提示 ...
	static public int INSTANCE_DESTROY_RST_COMBAT = 433;			// 你还战斗中，无法关闭副本...
	static public int INSTANCE_DESTROY_RST_UPDATE = 434;			// 更新副本人数时失败...
	static public int INSTANCE_DESTROY_RST_IS_NULL = 435;			// 副本不存在 ...
	static public int INSTANCE_PICKING_GENERAL_NO_FREE = 438;				// 当前没有空闲武将可以出征 ...
	static public int INSTANCE_BAIZHANBUDAI_ITEM_COST = 439;				// 消耗物品 ...
	static public int INSTANCE_NANZHENGBEIZHAN_ITEM_COST = 440;		// ...
	static public int INSTANCE_DESTROY_ASKING_OK = 441;				// 寻问结果 ...
	static public int INSTANCE_QUIT_RST_UNLOCK = 442;				// 副本还没解锁 ...
	
	
	// STC_GAMECMD_OPERATE_START_COMBAT_T
	static public int COMBAT_HERO_ISNULL 	= 100;
	static public int COMBAT_HERO_NOT_FREE 	= 101; 			// 武将不在空闲状态 ... 
	static public int COMBAT_NOT_END 			= 102; 			// 上次战斗还没有结束 ... 
	static public int COMBAT_NOT_LEADER			= 103;			// 队长才能发起战斗 ... 
	static public int COMBAT_OBJ_IS_NULL		= 104;			// 出征目标不存在 ...
	static public int COMBAT_RST_TYPE_IS_NULL	= 105;			// 战斗类型错误. ...
	static public int COMBAT_RST_PROTECT		= 106;			// 出征目标在保护期内,无法攻击....
	static public int COMBAT_RST_PVPQUEUE		= 107;			// 出征队列已满,请稍等 ...
	
	// STC_GAMECMD_OPERATE_STOP_COMBAT_T
	static public int COMBAT_DELETE			= 110;				// 副本被销毁 ... 
	static public int COMBAT_INSTANCE_FINISH	= 111;				// 副本通关 ... 
	static public int COMBAT_INSTANCE_OVER		= 112;				// 副本结束,重试次数使用完了 ... 
	
	// STC_GAMECMD_CREATE_INSTANCE_T
	static public int CREATE_INSTANCE_INNOW			= 120;				// 已经在副本中 ... 
	static public int CREATE_INSTANCE_ISNULL		= 121;				// 副本不存在 ... 
	static public int CREATE_INSTANCE_LEVEL			= 122; 			// 玩家等级未达到副本要求 ... 
	static public int CREATE_INSTANCE_OPENTIME		= 123;			// 副本冷却中 ... 
	static public int CREATE_INSTANCE_TIMES			= 124;			// 今天的免费次数和收费次数都用完了...
	static public int CREATE_INSTANCE_COST			= 125;			// 收费次数需要的消耗品没有了 ... 
	static public int CREATE_INSTANCE_RST_PLAYER	= 126;			// 副本队伍满员了 ....
	
	// STC_GAMECMD_START_INSTANCE_T
	static public int INSTANCE_START_NOT_LEADER			= 130;			// 只有队长才能开启副本 ...
	static public int INSTANCE_START_NOT_PREPARE		= 131;			// 玩家未准备就绪 ... 
	
	// STC_GAMECMD_PREPARE_INSTANCE_T
	static public int INSTANCE_PREPARE_NOT_HERO		= 132;			// 未配置武将 ... 
	
	// STC_GAMECMD_ROB_WORLDGOLDMINE_T
	static public int WORLDGOLDMINE_ROB_ISNULL			= 140;			// 金矿不存在... 
	static public int WORLDGOLDMINE_ROB_SAFETIME		= 141;			// 金矿还处在保护时间 ... 
	static public int WORLDGOLDMINE_ROB_NOT_COMBAT		= 142;			// 抢夺发起失败 ... 
	
	// STC_GAMECMD_GET_MY_WORLDGOLDMINE_T
	static public int WORLDGOLDMINE_MY_ISNULL			= 143;			// 你未占领任何金矿 ...
	
	// STC_GAMECMD_MANUAL_SUPPLY_T
	static public int WORLDGOLDMINE_SUPPLY_ISNULL		= 144;			// 世界金矿未配置武将 ...
	static public int INSTANCE_SUPPLY_ISNULL			= 145;			// 副本不存在 ...
	
	static public int INSTANCE_LOOT_ISNULL				= 146;			// 暂时未获取任何奖励 ...
	static public int INSTANCE_SUPPLY_NOFULL			= 147;			// 兵力不足,未能达到武将最大战力 ...
	static public int INSTANCE_SUPPLY_RST_NO_FREE		= 453;			// 武将不在空闲状态,未能得到补给 ...
	
	// STC_GAMECMD_DONE_QUEST_T
	static public int QUEST_DONE				= 130; 			// 任务已经完成了 ... 

	
}
